version: "3"
services:
  vite-app:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ../../app:/app
    networks:
      - default
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    environment:
      - VITE_NODE_ENV=development
      - VITE_BACKEND_URL=${BACKEND_URL}
    env_file:
      - ./.env

  core:
    build:
      context: ../../core
      target: dev # use the "dev" stage
    ports:
      - "3000:3000"
    volumes:
      - ../../core:/usr/src/app
    secrets:
      - target: ./secrets/mongo-creds.json
        source: mongo-creds-file
    networks:
      - default
    environment:
      - NODE_ENV=development
      - PORT=${BACKEND_PORT}
      - ORIGIN=${FRONTEND_URL}
    command: npm run dev

  mongo:
    image: mongo:latest
    networks:
      - default
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:

networks:
  default:
    driver: bridge

secrets:
  mongo-creds-file:
    file: ../../core/secrets/mongo-creds.json
