version: "3"
services:
  core:
    build:
      context: ../../core
      target: prod # use the "prod" stage
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    networks:
      - default
    volumes:
      - ../../core:/usr/src/app
    environment:
      - NODE_ENV=production
      - PORT=${BACKEND_PORT}
      - ORIGIN=${FRONTEND_URL}
    command: npm run start

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - default
    volumes:
      - mongo-data:/data/db

  ngrok:
    image: wernight/ngrok
    container_name: ngrok
    depends_on:
      - core
    command: ngrok http --url=${NGROK_URL} core:3001 --log=stdout

volumes:
  mongo-data:

networks:
  default:
    driver: bridge

secrets:
  mongo-creds-file:
    file: ../../core/secrets/mongo-creds.json
