version: '3'
services:
  vite-app:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./app:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: sh -c "npm install && npm run dev"
    environment:
      - NODE_ENV=development
    env_file:
      - ./.env
